### PR TITLE
Fixed arguments removal in python roscpp_initializer

### PR DESCRIPTION
**Pull request by ghost**
This problem prevented using moveit_commander with remapping of joint_states topic.

### CODE REVIEW

**Comment by mikeferguson** [comment]
This seems possibly problematic -- if using __name and using rospy.init_node(), roscpp_init will end up creating a nodehandle with the same name as the python nodehandle and causing the Python node to exit... 

I presume there is some other, better fix, but I'm not sure what your exact problem is -- perhaps answer here or open a new ticket for the problem?

**Comment by mikeferguson** [comment]
Whoops, I missed the fact that you added a line as well, which should do the same thing, sorry for the noise.

This is more pythonistic -- although, I'm not exactly sure how this fixes any problem as it should be doing the exact same thing, right? Now I'm definitely curious as to what your problem was and how this actually fixes it.

**Comment by HumaRobotics** [comment]
Actually, because strings are also lists in python the two codes are not equivalent. If you do:

> > > l=[]
> > > l+="sdf"
> > > l
> > > ['s', 'd', 'f']

So the string is broken up into a list of chars (and the same happens for the other parameters).
So the problem was that remapping arguments (or any argument whatsoever) were broken into chars and made unusable.
My first patch was to replace args2+=a  by args2.append(a), which works, but I thought using list comprehensions makes it nicer (and more pythonic indeed).

**Comment by mikeferguson** [comment]
Ah yes. +1

**Comment by e1000i** [comment]
±1 
I was suffering the remaping problem but could not find why was not working and switched to cpp due to lack of time. This is great. I will test on the robot monday,  but seems to me it will do the trick.

**Pull request merged**
