### PR TITLE
catkin_lint and cleanup

### PR DESCRIPTION
**Pull request by v4hn**
See ros-planning/moveit_core#298.

package.xml seemed to contain a whole lot of wrong entries.
I removed everything that didn't show up with `grep -r`.

### CODE REVIEW

**Comment by v4hn** [comment]
Please cherry-pick to later branches too (trivial in this case).

**Comment by v4hn** [comment]
@130s what's up with that build error in the warehouse module?

**Comment by davetcoleman** [comment]
+1

**Comment by 130s** [comment]
Failing for jade-shadow because travis job tries to compile source of `moveit_ros` (among other MoveIt! packages, based on [moveit.rosinstall](https://github.com/ros-planning/moveit_commander/blob/4e81e1b3a12fd431260d5970a92d148c5ba6c40e/.travis.yml#L48) file) and there seems to be a missing file issue. 

While I can track this down more, my question is whether we want to build other MoveIt! packages from source.

**Comment by 130s** [comment]
Turned out that source build for `moveit_ros` fails unless https://github.com/ros-planning/moveit_ros/pull/699 to be merged (or similar change needed) .

**Comment by v4hn** [comment]
On Tue, Jul 05, 2016 at 02:44:20PM -0700, Isaac I.Y. Saito wrote:

> Turned out that source build for `moveit_ros` fails unless https://github.com/ros-planning/moveit_ros/pull/699 to be merged (or similar change needed) .

... which in turn fails because moveit_ros_warehouse is not released yet.
Is this right?

**Comment by 130s** [comment]
@v4hn I'm not sure what you were asking, sorry, but if you mean why https://github.com/ros-planning/moveit_ros/pull/699 fails on Travis for now, see https://github.com/ros-planning/moveit_ros/pull/699#issuecomment-230622392

I don't feel like self-promoting but with industrial_ci we can easily handle source build, binary build, matrix them so that builds that is known to fail temporarily can be allowed. I once opened a PR but it's [reverted](https://github.com/ros-planning/moveit_commander/commits/indigo-devel/.travis.yml).

**Comment by davetcoleman** [comment]
the related moveit_ros_warehouse PRs have been merged, perhaps this can be merged too now? i just re-triggered the build

i'd recommend moveit_ci for this repo, too ;-)

**Comment by v4hn** [comment]
@davetcoleman build still fails with some warehouse issue.
Please go ahead and move to moveit_ci :-)

**Comment by davetcoleman** [comment]
Testing moveit_ci for indigo here https://github.com/ros-planning/moveit_commander/pull/49

**Comment by davetcoleman** [comment]
@v4hn can you rebase this with the new CI commit ?

**Comment by v4hn** [comment]
On Thu, Jul 21, 2016 at 01:28:00PM -0700, Dave Coleman wrote:

> @v4hn can you rebase this with the new CI commit ?

done

**Comment by davetcoleman** [comment]
Thanks! Need this in jade too

**Comment by v4hn** [comment]
picked into jade.

**Pull request merged**
