### PR TITLE
Added the calls necessary to manage path constraints. This commit

### PR DESCRIPTION
**Pull request by e1000i**
This is to close an issue that I open before.
https://github.com/ros-planning/moveit_commander/issues/18

I put my hands on and implemented it. 

To work depends on the changes commited to moveit_ros package to have access
to this functionalities.

If the pull request is accepted, this one should work fine also.
     https://github.com/ros-planning/moveit_ros/pull/438

Bassically now is possible to set the constraints as a moviet_msgs
Constraint message and retrieve an instance of the current path constraints
for a group.

### CODE REVIEW

**Comment by sachinchitta** [comment]
Thanks!

**Comment by mikeferguson** [comment]
@pirobot looks like moveit_commander is only 0.5.5 in hydro (http://www.ros.org/debbuild/hydro.html), so no, not in hydro yet.

**Comment by fivef** [comment]
@pirobot I wasn't sure in which repo to put this problem so I put it here because constraints seem to be the problem. 
I use the latest MoveIt hydro_devel from source. As soon as I add path constraints MoveIt stops with a segfault while planning. Without constraints everything works as expected. I have been debugging for several days now but wasn't able to find a solution yet. Moveit crashes in the KinematicsBase::initialize() function (see frame 3 below). The same function is called two times when move_group is started by the Kinematics plugin loader. Everytime with correct parameters. Only when I start a move group commander instance, add path constraints and start planning I get the backtrace below. 
Initialize is called with completely wrong addresses. The strange thing is that I can't find out where initialize is called from. Frame 4 says `moveit_planners/ompl/ompl_interface/src/parameterization/work_space/pose_model_state_space.cpp:175` put there I only find a call to `getTipFrame()`. Can someone tell me who calls initialize? Could this be a concurrence problem? Does anyone have a running moveit (latest hydro_devel from source) with path constraints enabled? 

```
#0 0x00007ffff55503b1 in _IO_vfprintf_internal (s=<optimized out>, format=<optimized out>, ap=<optimized out>) at vfprintf.c:1630
#1 0x00007ffff560e4c0 in ___vsnprintf_chk (s=0x7fffb2afc0e0 "moveit.kinematics_base: group_name: 18446744051160973318", maxlen=<optimized out>, flags=1, slen=<optimized out>, format=
0x7fffeb563ea8 "moveit.kinematics_base: group_name: %s", args=0x7fffb2afc0a8) at vsnprintf_chk.c:65
#2 0x00007ffff5de07bb in console_bridge::log(char const*, int, console_bridge::LogLevel, char const*, ...) () from /opt/ros/hydro/lib/libconsole_bridge.so
#3 0x00007fffeb561938 in kinematics::KinematicsBase::initialize (this=0x7fffa8032740, robot_description=<error reading variable: Cannot access memory at address 0x7fffb2afc6afe8>, group_name=
<error reading variable: Cannot access memory at address 0xec834853e589483d>, base_frame="", tip_frames=std::vector of length -22548578297, capacity -22548578303 = {...}, search_discretization=
0) at /home/iki/catkin_ws/src/moveit_core/kinematics_base/include/moveit/kinematics_base/kinematics_base.h:336
#4 0x00007fffc17df7de in ompl_interface::PoseModelStateSpace::PoseComponent::PoseComponent (this=0x7fffb2afc6d0, subgroup=0x7af4e0, k=...)
at /home/iki/catkin_ws/src/moveit_planners/ompl/ompl_interface/src/parameterization/work_space/pose_model_state_space.cpp:175
#5 0x00007fffc17deb33 in ompl_interface::PoseModelStateSpace::PoseModelStateSpace (this=0x7fffa80302a0, spec=...)
at /home/iki/catkin_ws/src/moveit_planners/ompl/ompl_interface/src/parameterization/work_space/pose_model_state_space.cpp:48
#6 0x00007fffc17e637d in ompl_interface::PoseModelStateSpaceFactory::allocStateSpace (this=0x3777f10, space_spec=...)
at /home/iki/catkin_ws/src/moveit_planners/ompl/ompl_interface/src/parameterization/work_space/pose_model_state_space_factory.cpp:87
#7 0x00007fffc17de374 in ompl_interface::ModelBasedStateSpaceFactory::getNewStateSpace (this=0x3777f10, space_spec=...)
at /home/iki/catkin_ws/src/moveit_planners/ompl/ompl_interface/src/parameterization/model_based_state_space_factory.cpp:41
#8 0x00007fffc176b1aa in ompl_interface::PlanningContextManager::getPlanningContext(planning_interface::PlannerConfigurationSettings const&, boost::function<boost::shared_ptr<ompl_interface::ModelBasedStateSpaceFactory> const& (std::string const&)> const&) const (this=0x2d0ce50, config=..., factory_selector=...)
at /home/iki/catkin_ws/src/moveit_planners/ompl/ompl_interface/src/planning_context_manager.cpp:222
#9 0x00007fffc176c25b in ompl_interface::PlanningContextManager::getPlanningContext (this=0x2d0ce50, planning_scene=
(boost::shared_ptr<planning_scene::PlanningScene const>) (count 5, weak count 2) 0x2d16710, req=..., error_code=...)
at /home/iki/catkin_ws/src/moveit_planners/ompl/ompl_interface/src/planning_context_manager.cpp:349
#10 0x00007fffc175fe9f in ompl_interface::OMPLInterface::getPlanningContext (this=0x2d0cda0, planning_scene=
(boost::shared_ptr<planning_scene::PlanningScene const>) (count 5, weak count 2) 0x2d16710, req=..., error_code=...)
at /home/iki/catkin_ws/src/moveit_planners/ompl/ompl_interface/src/ompl_interface.cpp:108
#11 0x00007fffc841dfa5 in ompl_interface::OMPLPlannerManager::getPlanningContext (this=0x3776fc0, planning_scene=
(boost::shared_ptr<planning_scene::PlanningScene const>) (count 5, weak count 2) 0x2d16710, req=..., error_code=...)
at /home/iki/catkin_ws/src/moveit_planners/ompl/ompl_interface/src/ompl_plugin.cpp:106
#12 0x00007fffefe317a4 in planning_request_adapter::(anonymous namespace)::callPlannerInterfaceSolve (planner=0x3776fc0, planning_scene=
(boost::shared_ptr<planning_scene::PlanningScene const>) (count 5, weak count 2) 0x2d16710, req=..., res=...)
at /home/iki/catkin_ws/src/moveit_core/planning_request_adapter/src/planning_request_adapter.cpp:52
```

**Comment by fivef** [comment]
Ok, so at least I am not alone. @davetcoleman could you help us concerning the last two posts? You seem to be quite into Kinematics Base.

**Comment by davetcoleman** [comment]
I'm confused by the statement 

> NOTE: This bug does not exist in shadow fixed. And in the latest binary release Debs, a different bug exists (but is fixed in shadow fixed):

and 

> I am also seeing this bug when compiling moveit-core, moveit-ros and moveit-commander from source and using the Python interface to MoveIt Commander.

I never use MoveIt commander and avoid python as much as possible, but I could take a look if you give me exact instructions to reproduce the bug with a particular robot's URDF and moveit_config package

**Comment by fivef** [comment]
Sounds great! Thanks Dave for the offer! As it works now for pirobot I will
try this asap. @pirobot perhaps the problem somehow wasn't related to the
packages we had installed from source. This would explain why it works now
also from source. Another question: Which ik and which planner do you use?
Are orientation constraints useable for you? I had only tried it with
RRTConnect and KDL with very bad results. Actually I was only able to
really generate a feasible trajectory once. Now I wanted to give it a
second shot with Levenberg-Marquard ik when this problem occurred.

2014-07-22 16:46 GMT+02:00 pirobot notifications@github.com:

**Pull request merged**
